### ISSUE TITLE
Week of April 24th 2019

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#10]
### Todo
---
#### 1. collect information
   - [ ] what was the reason why the blending frequency of the L(,T) and Y was different.
   - [ ] what is ongoing? for Type-A/B/Bp
   - [ ] tasks for hierarchical control?
---
#### 2. summarize the Lucia's blending performance
  - [ ] check the frequencies of the notch in IP_TF, and the residual peak in BF_L(/T).
  - [ ] check the sensor noise level of the BF-LVDT
  - [ ] check the OLTFs for all the implemented loops
---
#### 3. build mechanical simulation models
- [x] collect mechanical TFs
  - [x] for ETMX
  - [x] for ETMY
  - [x] for ITMX
  - [x] for ITMY
---
- [ ] build mechanical models
  - [ ] for ETMX
  - [ ] for ETMY
  - [ ] for ITMX
  - [ ] for ITMY
---
#### 4. check the coherence (for ITMY)
  - [x] between IP and GND
  - [x] between BF-LVDTs and GND

  - [ ] try to make test filters for IPL/IPT

**Comment by YoshinoriFujii** [comment]
### Todo
#### 5. make a list of wanted results for the thesis.
Target: To characterize/evaluate the suspensions (for mainly Type-A)
- In terms of the vibration isolation performance
  - measure the TF from GND to DARM for each suspension.
    -  w/ controls
    - (w/o controls)

- In terms of the damping loop performance
  - measure the decay-time constants
  - measure residual spectra.
  - dominant mode? for lock loss?

##### For the preparation of the above, what is remaining?
  - hierarchical controls?
  -

**Comment by YoshinoriFujii** [comment]
> 3. build mechanical simulation models
>     collect mechanical TFs 

The data is stored in:
`/users/VIS/TypeA/general/measurement_for_modeling`

- [ ] make plots

**Comment by YoshinoriFujii** [comment]
> 4. check the coherence (for ITMY)
>     between IP and GND
>     between BF-LVDTs and GND

- The data is stored in:
`/users/VIS/TypeA/ITMY/measurement/IP_ACC/190425/ACC_monitor_190425.xml`
- This was measured when the damping with IP-LVDT and BF-Y were closed.
- [ ] Try to subtract the seismic noise?

![coherence_190425](https://user-images.githubusercontent.com/37787512/56722591-5e7a6600-6782-11e9-8d9a-7ba2b64d8140.png)

**Comment by YoshinoriFujii** [comment]
Note:
dir of the sysid scripts:
`/kagra/Dropbox/Subsystems/VIS/Scripts/SuspensionControlModel/sysid/`
