### ISSUE TITLE
Geophone calibration for BS

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#11]
### Target
- Get the calibration parameters from this data:
![geo_monitor_plots_190123_2225JST](https://user-images.githubusercontent.com/37787512/57290663-d0df3480-70f8-11e9-9157-6cc83abadd56.png)

### Todo
- [x] plot transfer functions from output voltage to the velocity of the mass
- [x] get the information of t_deacay, f0, Ge by fitting the function with the eq in [1].
- [ ] estimate the noise level with 3-channel correlation analysis.

reference:
[1] [geo-tf](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/TypeA/ETMX "geo-tf2")

**Comment by YoshinoriFujii** [comment]
The measurement data is stored in
`/users/VIS/TypeB/geo_check/forBS/190123/`

**Comment by YoshinoriFujii** [comment]
> plot transfer functions from output voltage to the velocity of the mass
> get the information of t_deacay, f0, Ge by fitting the function with the eq in [1].

The fitting results (raw) are:
[fitting_results_for_BS.pdf](https://github.com/YoshinoriFujii/Weekly-task/files/3152177/fitting_results_for_BS.pdf)

| channel name | Ge  | eta  | f0 |
| :---: | :---: | :---: |  :---: |
| CH20 | 269.916375915 +/- 0.000188587927379 | 0.346571105434 +/- 3.00711943235e-07 |0.983204011539 +/- 1.71568859765e-07 |
| CH21 | 269.306243386 +/- 0.000182615347757 | 0.340087429364 +/- 2.88354030819e-07 | 0.987126563661 +/- 1.68207920156e-07 | 
| CH22 | 270.38483948 +/- 0.000185564029199 | 0.33709611255 +/- 2.79657468877e-07 | 1.0171297833 +/- 1.69051499483e-07 | 
| CH23 | 273.233487731 +/- 0.000192338064131 | 0.277733478285 +/- 2.27452910585e-07 | 1.23137542287 +/- 1.44064917327e-07 | 

[TF_geo_BS_CH20.txt](https://github.com/YoshinoriFujii/Weekly-task/files/3152206/TF_geo_BS_CH20.txt)
[TF_geo_BS_CH21.txt](https://github.com/YoshinoriFujii/Weekly-task/files/3152205/TF_geo_BS_CH21.txt)
[TF_geo_BS_CH22.txt](https://github.com/YoshinoriFujii/Weekly-task/files/3152203/TF_geo_BS_CH22.txt)
[TF_geo_BS_CH23.txt](https://github.com/YoshinoriFujii/Weekly-task/files/3152202/TF_geo_BS_CH23.txt)
