### ISSUE TITLE
Week of  May 9th 2019

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#12]
### Todo
- [ ] make todo list
- [ ] build models for typeA suspensions
- [ ] summarize the filters in the Type-A/B/Bp
- [ ] Add a part for seismic noise subtraction for PRM RT-model.
