### ISSUE TITLE
Week of 20th May 2019

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#15]
### Todo
---
#### For FF campaign
- [ ] add a channel SEIS_X to BF_P
    - [ ] try to extract the seismic noise from BF_P and see what happens to the TM_L/P/Y
- [x] Add SEIX_X/Y/Z channel to PRM model.

---
### For TypeA control information tiding up campaign
- [ ] build/tune the four suspension models
- [ ] investigate the 80mHz coupling when the inertial damping is closed.
    - [ ] check the coupling ratio of the each transfer function.
    - [ ] check the spectra with certain filters.
