### ISSUE TITLE
Type-A tower performance check

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#17]
### Todo
- [ ]  compare the spectra:
  - [ ] w/ LVDT_damping
     - [x] IX
     - [x] IY, see `${dir}/ITMY/Measurements/20190602/ITMY_mointor_w_LVDT-damping.xml` [1] 
     - [x] EX, see `${dir}/ETMX/Measurements/Spectra/20190605/ETMX_monitor_w_LVDT-damping_0743JST.xml` [1]
     - [ ] EY
  - [x] w/ Inertial damping
     - [x] IX, see `${dir}/ITMX/Measurements/20190602/ITMX_mointor_w_inertial-damping.xml` [1] 
     -  ~IY~
     - [x] EX, see `${dir}/ETMX/Measurements/Spectra/20190602/ETMX_mointor_w_inertial-damping.xml` [1] 
     - [x] EY, see `${dir}/ETMY/Measurements/Spectra/20190602/ETMY_mointor_w_inertial-damping.xml` [1] 
---

- [ ] check the filters for all the dofs.

- [ ] check the OLTFs for all the dofs.

---

- [ ] check the CLTFs for all the dofs.

- [ ] check the (mechanical) TFs for all the dofs.

---

- Reference
  - [1] /users/VISsvn/TypeAtower

**Comment by YoshinoriFujii** [comment]
**= IX =**
- Measured spectra w/ inertial damping, w/o GAS controls:


![image](https://user-images.githubusercontent.com/37787512/58756181-03c8ec80-852e-11e9-9024-7bf1426a24f5.png)

![image](https://user-images.githubusercontent.com/37787512/58756186-15aa8f80-852e-11e9-9875-67bf612e1f41.png)

![image](https://user-images.githubusercontent.com/37787512/58756189-2c50e680-852e-11e9-819d-995c0961777f.png)

---

- Measured BF-Yaw-excited transfer function w/ inertial damping, w/o GAS controls, w/ BF-Y to BF-Y damping control:


![image](https://user-images.githubusercontent.com/37787512/58756203-68844700-852e-11e9-8800-0bdf696110af.png)


---

- Measured spectra w/o any damping, w/o GAS controls:

![image](https://user-images.githubusercontent.com/37787512/58757716-18b47880-854c-11e9-8f00-e21d469111e6.png)

![image](https://user-images.githubusercontent.com/37787512/58757734-65984f00-854c-11e9-9731-207d6f06d464.png)

![image](https://user-images.githubusercontent.com/37787512/58757741-7c3ea600-854c-11e9-8fb5-c629036e2d96.png)


---

- Measured spectra w/ LVDT damping, w/o GAS controls:


![image](https://user-images.githubusercontent.com/37787512/58758260-cf682700-8553-11e9-8854-ebb7da96465a.png)

![image](https://user-images.githubusercontent.com/37787512/58758297-8cf31a00-8554-11e9-8e83-2f014b86d6e0.png)

![image](https://user-images.githubusercontent.com/37787512/58758304-9a100900-8554-11e9-84b2-3df3bc541011.png)


---

- Measured BF-Yaw-excited transfer function w/ LVDT damping, w/o GAS controls, w/ BF-Y to BF-Y damping control:

![image](https://user-images.githubusercontent.com/37787512/58758829-5faa6a00-855c-11e9-8807-12cf28d3f9d9.png)

--- 

- Measured spectra w/ LVDT damping, w/ INT-BF-Y control, w/o GAS controls:

![Screenshot from 2019-06-04 10:47:55](https://user-images.githubusercontent.com/37787512/58845494-5fbe7d00-86b6-11e9-9b45-b2b1c5bbd174.png)

![ITMX_w_LVDT-damping_w-INT-BFY_wo-GAS](https://user-images.githubusercontent.com/37787512/58846694-102e8000-86bb-11e9-942b-fddedaa5a718.png)

--- 

- Measured BF-Yaw-excited transfer function w/ LVDT damping, w/o GAS controls, w/ BF-Y to BF-Y **_DC_** control:

![BF_Yexc_w_LVDT-INT-damping](https://user-images.githubusercontent.com/37787512/58846712-26d4d700-86bb-11e9-9d3d-bf4fdc10311b.png)

**Comment by YoshinoriFujii** [comment]
**= IY =**
- Measured spectra w/ LVDT damping, w/o GAS controls:

![image](https://user-images.githubusercontent.com/37787512/58756335-8dc68480-8531-11e9-8191-81de3147b9d4.png)

![image](https://user-images.githubusercontent.com/37787512/58756339-a767cc00-8531-11e9-80f4-9dbaf6767327.png)


![image](https://user-images.githubusercontent.com/37787512/58756343-bbabc900-8531-11e9-9c7b-62aaf20a1819.png)

**Comment by YoshinoriFujii** [comment]
**= EX =**
- Measured spectra w/ inertial damping, w/o GAS controls:

![image](https://user-images.githubusercontent.com/37787512/58756472-3b3a9780-8534-11e9-86b4-c2c2ff01ae25.png)


![image](https://user-images.githubusercontent.com/37787512/58756481-67eeaf00-8534-11e9-8ee2-ab80ca129b20.png)

![image](https://user-images.githubusercontent.com/37787512/58756511-d2075400-8534-11e9-91bd-8ec36e3cfcda.png)

---
- Measured spectra w/ LVDT damping, w/o GAS controls:


![ETMX_monitor_w_LVDT-damping](https://user-images.githubusercontent.com/37787512/58927396-53572480-8789-11e9-9761-16884971a3b9.png)

![Screenshot from 2019-06-05 17:36:49](https://user-images.githubusercontent.com/37787512/58942433-b613e480-87b8-11e9-82ce-83f01b0ffc04.png)

**Comment by YoshinoriFujii** [comment]
**= EY =**
- Measured spectra w/ inertial damping, w/o GAS controls:


![image](https://user-images.githubusercontent.com/37787512/58756600-a9805980-8536-11e9-94b7-f0d162d9d7c1.png)

![image](https://user-images.githubusercontent.com/37787512/58756606-d9c7f800-8536-11e9-9ba2-a6eeb952a621.png)

![image](https://user-images.githubusercontent.com/37787512/58756610-e8161400-8536-11e9-83a9-8213ec137729.png)
