### ISSUE TITLE
Week of June 2nd

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#18]
### Todo
- measure the the following spectra for each suspension:
  - [x] w/ inertial damping
     - [x] IX, see `${dir_t}/ITMX/Measurements/20190602/ITMX_mointor_w_inertial-damping.xml` [1] 
     -  ~IY~
     - [x] EX, see `${dir_t}/ETMX/Measurements/Spectra/20190602/ETMX_mointor_w_inertial-damping.xml` [1] 
     - [x] EY see `${dir_t}/ETMY/Measurements/Spectra/20190602/ETMY_mointor_w_inertial-damping.xml` [1] 
  - [ ] w/ LVDT damping
     - [ ] IX
     - [ ] IY, see `${dir_t}/ITMY/Measurements/20190602/ITMY_mointor_w_LVDT-damping.xml` [1] 
     - [ ] EX
     - [ ] EY
  - [ ] w/o damping
     - [x] IX
     - [ ] IY
     - [ ] EX
     - [ ] EY
- [ ] measure the time series of IPs in L and the seismometers of all the suspensions w/o control.

- measure TF of BF-LVDT in L and Y
  - [ ] w/ inertial damping
     - [ ] IX
     -  ~IY~
     - [ ] EX
     - [ ] EY
  - [ ] w/ LVDT damping
     - [ ] IX
     - [ ] IY
     - [ ] EX
     - [ ] EY
  - [ ] w/o damping
     - [ ] IX
     - [ ] IY
     - [ ] EX
     - [ ] EY

- [ ] modify the BF-Yaw filter for ITMX.

- [ ] adjust the GAS positions and close the control loops.

- [x] Measure IM to TM transfer functions in P/Y
     - [x] IX, see `${dir_p}/ITMX/TF/Measurements/20190603/IMexc/` [2]
     - [x] IY, see `${dir_p}/ITMY/TF/Measurements/21090603/IMexc/` [2]
     - [x] EX, see `${dir_p}/ETMX/TF/Measurement/20190603/IMexc/` [2]
     - [x] EY, see `${dir_p}/ETMY/TF/Measurements/20190603/IMexc/` [2]

---
- Reference
  - [1] dir_t=/users/VISsvn/TypeAtower/
  - [2] dir_p=/users/VISsvn/TypeApayload/

**Comment by YoshinoriFujii** [comment]
- [ ] check the following GASs and fix them definitely mechanically.

**Comment by YoshinoriFujii** [comment]
### prep
- I opened the following filters, about the payload:

  - K1:VIS-ETMY_TM_LOCK_L, HPF1, with 1.

= IX =
- TMY2P01, P01 to MNY, for 0.34Hz, with 1
- TMYP02, P02 to TMY, for 3.23Hz, with 0.3
- TMY2P03, P03 to MNY, for 0.082Hz, with 100
![image](https://user-images.githubusercontent.com/37787512/58754434-be46f800-850a-11e9-9e4d-ba4d27db9228.png)


= EX =
- TMY2P01, P01 to MNY, for 0.327Hz, with 4
![image](https://user-images.githubusercontent.com/37787512/58754446-f2bab400-850a-11e9-9fe2-2cb572fb7ac1.png)


= IY =
- It seemed nothing was registered today.


= EY =
- TML2P01, P01 to 0, for 0.632Hz, with 1
- TML2P02, P02 to 0, for 0.632Hz, with 1
- TML2P03, P03 to 0 , for 1.67Hz, with 1
- TMY2P04, P04 to MNY, for 1.69Hz, with 1
- TMY2P05, P05 to MNY, for 0.34Hz, with 1
- TMY2P06, P06 to TMY , for 3.21Hz, with 1
- TMP2P07, P07 to MNP, for ~3.21Hz~ 0.85Hz, with 1
- TMP2P08, P08 to TMP, for 7.57Hz, with 1
- TMY2P09, P09 to TMY , for 1.67Hz, with 200


![image](https://user-images.githubusercontent.com/37787512/58754455-2a296080-850b-11e9-9315-9757de9289ff.png)



---

- reference

![image](https://user-images.githubusercontent.com/37787512/58754393-eda93500-8509-11e9-8238-e5bd9d3ab0fd.png)

**Comment by YoshinoriFujii** [comment]
see [Weekly-task/issues/17](https://github.com/YoshinoriFujii/Weekly-task/issues/17 "Weekly-task/issues/17")

### ITMX

---
#### PRACTICAL NOTES 

- From 13:16JST, 
  - trying to switch off the inertial-damping and turn on the LVDT damping:
    - off-load `K1:VIS-ITMX_IP_DAMP_L_OUTPUT` using `K1:VIS-ITMX_IP_COILOUTF_{H1/H2/H3}_OFFSET`.
    - Before:
![image](https://user-images.githubusercontent.com/37787512/58756737-860ade00-8539-11e9-95dd-b91f4bc661fb.png)

    - After:
![image](https://user-images.githubusercontent.com/37787512/58756841-febe6a00-853a-11e9-8761-78ebcc3925e9.png)

    - opened BF-Yaw damping control
    - opened IP-L/T/Y inertial-damping controls, 3 of them.
    - opened blending loops:
      - Before
![image](https://user-images.githubusercontent.com/37787512/58757169-3b419400-8542-11e9-9960-97a12c411f64.png)
      - After
![image](https://user-images.githubusercontent.com/37787512/58757198-1b5ea000-8543-11e9-9e71-8930f250f85f.png)

**Comment by YoshinoriFujii** [comment]
### On June 3rd
10:06JST
- IY
![image](https://user-images.githubusercontent.com/37787512/58770035-5ca88b80-85e7-11e9-9098-9d67b7b2721f.png)

- EX
![image](https://user-images.githubusercontent.com/37787512/58770363-72b74b80-85e9-11e9-94bb-22117352f171.png)

---

**Comment by YoshinoriFujii** [comment]
### EX
- before
![Screenshot from 2019-06-04 21:06:51](https://user-images.githubusercontent.com/37787512/58877812-b656a600-870c-11e9-90a8-eab97c6c61d1.png)

![Screenshot from 2019-06-04 21:07:38](https://user-images.githubusercontent.com/37787512/58877875-de460980-870c-11e9-9f29-120dd5c2df82.png)
