### ISSUE TITLE
check current situation including SC

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#20]
### Todo

~[1]~ what is the difference of the IPdcdamp filters, and what was happened on the spectra with those filters?

---
[2] check the actual performance of the following configuration during the silent run: 
   - IPdcdamp
   - IPdcdamp + IPsc
   - IPdcdamp + IPsc + BFdamp
   - IPdcdamp + IPsc + BFdamp + BFsc
   - [ ] check with TY

---
~[3]~ check the gain of the IPdcdamp loop when the IPsc is engaged.

---
[4] simulate the Q-factors and if the tower-modes meet the requirement.

---
~[5]~ confirm if the sensor-corrected at TMoplev can see the TM motion
  - [x] extract the timeseries at 17/09/2019/07:55:58 UTC

**Comment by YoshinoriFujii** [comment]
> [5] confirm if the sensor-corrected at TMoplev can see the TM motion

see `/users/VIS/TypeA/general/rms_suppression/20190918/20190917JST/`
Tips: https://gwpy.github.io/docs/stable/api/gwpy.timeseries.TimeSeries.html

- It seems yes in the range from about 150mHz to 500mHz.
![result_w_seisSC_ETMX_](https://user-images.githubusercontent.com/37787512/65136594-c9cf1800-da42-11e9-8055-049ed9605494.png)

- For next, compare with the simulation:
  - [x] w/ IPdcdamp + IPsc

  => see `/kagra/Dropbox/Personal/Fujii/TypeA/simulation/figures/*/IPdcdamp_20190903_IPLsc_20190917_seis/`

---

### Wrong! the ground was not in disp!
![spectrum_TML_IPdcdamp_20190903_IPLsc_20190917_seis](https://user-images.githubusercontent.com/37787512/65149502-2b9c7b80-da5d-11e9-9117-3974ee709345.png)

[noise_coupling_disp_toTMLoplev_IPdcdamp_20190903_IPLsc_20190917_seis.pdf](https://github.com/YoshinoriFujii/Weekly-task/files/3626406/noise_coupling_disp_toTMLoplev_IPdcdamp_20190903_IPLsc_20190917_seis.pdf)

---
### Correct!
![spectrum_TML_IPdcdamp_20190903_IPLsc_20190917_seis](https://user-images.githubusercontent.com/37787512/65209868-478f3400-dad4-11e9-9a47-092a51643b0c.png)

[noise_coupling_disp_toTMLoplev_IPdcdamp_20190903_IPLsc_20190917_seis.pdf](https://github.com/YoshinoriFujii/Weekly-task/files/3629143/noise_coupling_disp_toTMLoplev_IPdcdamp_20190903_IPLsc_20190917_seis.pdf)


---

 - [x] compare the simulation and the measurement
- see `/kagra/Dropbox/Personal/Fujii/TypeA/simulation/scripts/exe_plot_20190917_performance.py`
- see also `/kagra/Dropbox/Personal/Fujii/TypeA/simulation/figures/measurement_comp/IPdcdamp_20190903_IPLsc_20190917_seis/comp_local_ETMX_TM_IPsc-on.png
`

![comp_local_ETMX_TM_IPsc-on](https://user-images.githubusercontent.com/37787512/65210283-9be6e380-dad5-11e9-9b67-0a92e622bd39.png)

- It seemed that the correction of TMoplev with seismometer did not work well..
 - [ ] calibration factor would be suspicious?

- It would not be a good idea to use the length oplev as the local sensor when the ground motion is quiet..
  - When the ground motion is quiet, only the sensors would be the cavities..

**Comment by YoshinoriFujii** [comment]
> [3] check the gain of the IPdcdamp loop when the IPsc is engaged.

- see `/kagra/Dropbox/Personal/Fujii/TypeA/simulation/figures/*/${config}/`
where config is:
  - IPdcdamp_20190903_IPsc*
---
### In simulation side:
  - w/ IPdcdamp, w/o IPLsc

![IPL2IPL_IPdcdamp_20190903_IPsc_gain1](https://user-images.githubusercontent.com/37787512/65141871-7a8de500-da4c-11e9-910d-aaf5f9a04dfc.png)

IPdcdamp_gain = 0.5 and 1
![IPdcdamp-forIPsc_gain_comp](https://user-images.githubusercontent.com/37787512/65141834-634ef780-da4c-11e9-84c6-9e63bb7be184.png)

---
  - w/ IPdcdamp, w/ IPLsc-ideal
  - `/kagra/Dropbox/Personal/Fujii/TypeA/simulation/figures/*/IPsc_gain_comp`
IPdcdamp_gain = 0.5 and 1
![IPdcdamp-forsc_IPsc_gain_comp](https://user-images.githubusercontent.com/37787512/65142136-fe47d180-da4c-11e9-88e7-e0161e60abd5.png)

**Comment by YoshinoriFujii** [comment]
> [1] what is the difference of the IPdcdamp filters, and what was happened on the spectra with those filters?

- see `/kagra/Dropbox/Personal/Fujii/TypeA/simulation/figures/sensor_noise_couling/IPdcdamp_asis_comp`

- w/ asis-IPdcdamp filter
![IPL2IPL_IPdcdamp_asis](https://user-images.githubusercontent.com/37787512/65145010-87620700-da53-11e9-944b-b0f413f92ad6.png)

- w/o IPLsc <- | ->  w/ IPLsc 
![IPdcdamp_asis_comp](https://user-images.githubusercontent.com/37787512/65144907-45d15c00-da53-11e9-8b6d-bf69f2cb4e88.png)

---
- w/ 20190903-IPdcdamp filter
![IPL2IPL_IPdcdamp_20190903_IPsc](https://user-images.githubusercontent.com/37787512/65145077-a19be500-da53-11e9-83dd-1f3acaa9b28a.png)

- w/o IPLsc <- | ->  w/ IPLsc 
![IPdcdamp_20190903_IPsc_comp](https://user-images.githubusercontent.com/37787512/65145109-b2e4f180-da53-11e9-94d4-6ca6f1ee10c3.png)

---
- According to the simulation, asis-filter+IPsc will increas the RMS because of the sc-filter gain at 30mHz. For this point of view, it would be better to use the 20190903-filter though, the hight of the peak at about 150mHz is mostly same..
  - [ ] Does this change if vertical motion is suppressed?

**Comment by YoshinoriFujii** [comment]
Tip: enumerate ehttps://python.civic-apps.com/zip-enumerate/
