### ISSUE TITLE
performance check of seismometerSC

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#23]
### todo
- [x] IPdcdamp
- [x] IPdcdamp + IPsc
- [x] IPdcdamp + IPsc + BFdamp
- [x] IPdcdamp + IPsc + BFdamp + BFsc

**Comment by YoshinoriFujii** [comment]
### IPdcdamp + IPsc + BFdamp
- at 06:18JST started
- [x] for 45min total at least.

![congif_0630JST](https://user-images.githubusercontent.com/37787512/65187671-60352500-daa7-11e9-945d-67e8d5d69047.png)

---
from ~06:25 to 06:45 

![IPdcdamp_IPsc_BFdamp_Xarm-locked](https://user-images.githubusercontent.com/37787512/65188264-fb7aca00-daa8-11e9-8d08-1203a8df5e6d.png)

 to 0721 JST

**Comment by YoshinoriFujii** [comment]
### IPdcdamp + IPsc + BFdamp + BFsc
- at 07:22JST started 
- [x] for 45min total at least.

![IPdcdamp_IPsc_BFdamp_BFsc_Xarm-locked](https://user-images.githubusercontent.com/37787512/65191917-67acfc00-dab0-11e9-8ca3-d95332be2fcd.png)

- When BFsc was off -> on:
![BFsc_on-off_20190919](https://user-images.githubusercontent.com/37787512/65192026-bfe3fe00-dab0-11e9-908e-b92cb48a8f55.png)

until 08:25JST

**Comment by YoshinoriFujii** [comment]
### IPdcdamp + IPsc
- at 08:28JST started
- [x] for 45min total at least.

![IPdcdamp_IPsc_Xarm-locked](https://user-images.githubusercontent.com/37787512/65197067-98932e00-dabc-11e9-9845-e3f2750ffb0c.png)

for a quick check:
![Xarm_comp_20190919](https://user-images.githubusercontent.com/37787512/65197150-eb6ce580-dabc-11e9-87e3-e73fd2a67903.png)

until 09:24 JST

**Comment by YoshinoriFujii** [comment]
Tips: Plotting transfer function w/ Gwpy:
https://gwpy.github.io/docs/v0.1/examples/gw_ex_plot_transfer_function.html

**Comment by YoshinoriFujii** [comment]
Brief summary, to be updated:
- see `/users/VIS/TypeA/general/rms_suppression/20190919/*/`
---
![result_Sep-19-2019-06-25-00-JST_performance_2pannels](https://user-images.githubusercontent.com/37787512/65241424-73cfa280-db1e-11e9-8a0f-8fb0e1a59e31.png)
---
![result_Sep-19-2019-07-25-00-JST_performance_2pannels](https://user-images.githubusercontent.com/37787512/65241437-77fbc000-db1e-11e9-9cc2-d394cdb2534d.png)
---
![result_Sep-19-2019-08-30-00-JST_performance_2pannels](https://user-images.githubusercontent.com/37787512/65241448-7c27dd80-db1e-11e9-972e-1abb9dc02467.png)
---
![comp_Xarm_20190919](https://user-images.githubusercontent.com/37787512/65244065-ac727a80-db24-11e9-97e1-73b2838d6ac4.png)

---
- [x] add local performance

**Comment by YoshinoriFujii** [comment]
btw, average_fft is commonly used one?

**Comment by YoshinoriFujii** [comment]
> add local performance

generated the coherence .txt files by:
`/users/VIS/TypeA/general/rms_suppression/20190919/scripts/global/exe_plot_20190919_performance.py`
the data is stored in:
`/users/VIS/TypeA/general/rms_suppression/20190919/IPdcdamp_IPsc_BFdamp/data_files/coh/`

[updates190920.pdf](https://github.com/YoshinoriFujii/Weekly-task/files/3635490/updates190920.pdf)

**Comment by YoshinoriFujii** [comment]
> add local performance

generated the coherence .txt files by:
`/users/VIS/TypeA/general/rms_suppression/20190919/scripts/global/exe_plot_20190919_performance.py`
the data is stored in:
`/users/VIS/TypeA/general/rms_suppression/20190919/IPdcdamp_IPsc_BFdamp/data_files/coh/`

Tips: enumerate https://python.civic-apps.com/zip-enumerate/

**Comment by YoshinoriFujii** [comment]
## The work is restarted
### 2019.9.21
- How to lock IR
  => ref: SASLIGNMENT.adl, after putting all oplevs to the good reference (for Xarm, IY should be misaligned), and request "Aign IRX", then request "IR_ARM_LOCK" in "SC_SRFPMI_LOCK".

- at 05:50 JST, IR at X-arm was locked.

**Comment by YoshinoriFujii** [comment]
### IPdcdamp
- at 06:16 started.

![config_2019-09-21-06-17-42](https://user-images.githubusercontent.com/37787512/65359510-a4572f80-dc37-11e9-9395-44cb21591657.png)

![quick_result_20190921_IPdcdamp_0648JST](https://user-images.githubusercontent.com/37787512/65360680-d36fa000-dc3b-11e9-888b-75ffea12497f.png)

![ocean_activity_2019-09-21-6hJST](https://user-images.githubusercontent.com/37787512/65361924-69a5c500-dc40-11e9-969d-4a189dc5f3d5.png)


until 07:21JST

**Comment by YoshinoriFujii** [comment]
### IPdcdamp + IPsc
- At 07:25 started

![config_2019-09-21-07-23-46](https://user-images.githubusercontent.com/37787512/65362085-154f1500-dc41-11e9-83a0-d661fa3a7454.png)

- When the IPsc was started (at 07:25JST):
![IPsc_started_EX-IX_2019-09-21-07-30-46](https://user-images.githubusercontent.com/37787512/65362345-f7ce7b00-dc41-11e9-8646-b9f7093c77e1.png)

- From 07:21 to 07:51 JST:
![quick_result_IPdcdamp_IPsc_0752JST](https://user-images.githubusercontent.com/37787512/65363014-c99e6a80-dc44-11e9-8ead-9357dd887282.png)

- It looked that the peak at 155mHz is not from the IP-L motion at least.

---
- At 07:53 BFsc started:
![config_2019-09-21-07-54-32](https://user-images.githubusercontent.com/37787512/65363094-2437c680-dc45-11e9-8456-fe587298dfe6.png)

- From 07:55 to 08:23 JST:
![quick_resut__IPdcdamp_IPsc_0823JST png](https://user-images.githubusercontent.com/37787512/65365202-80551780-dc52-11e9-8852-33db363ea1b7.png)

**Comment by YoshinoriFujii** [comment]
### IPdcdamp + IPsc + BFdamp + BFsc
- at 08:25
  - ETMX-BFdamp-L/T was on.
---
- ITMX-BFL was modified since larger noise was to be injected with the implemented filter: 
![ITMX_BFdamp_L_modification-test_0900JST](https://user-images.githubusercontent.com/37787512/65366025-cf527b00-dc59-11e9-961b-26d27e5f8c12.png)

  - K1:VIS-ITMX_BF_DAMP_L_OUT w/ SW-off, before/after changing the filter:
![ITMX_BFdamp_L_modification-test_0900JST_timeseries](https://user-images.githubusercontent.com/37787512/65366031-dda09700-dc59-11e9-807a-0403da067cb9.png)
  - the spectra before(upper) / after(lower):
![ITMX_BFdamp_L_modification-test_OUTPUT_0900JST](https://user-images.githubusercontent.com/37787512/65366034-e09b8780-dc59-11e9-828d-0ea1c34f96d0.png)

 - [ ] Add some notches and increase the gain at ~150,Hz. => try to tune again.

---
- at 09:00
  - ITMX-BFdamp-L/T was on.

![config_IPdcdamp_IPsc_BFdabp_BFsc_2019-09-21-09-13-55](https://user-images.githubusercontent.com/37787512/65364944-42ef8a80-dc50-11e9-88a9-591810a6584d.png)

- At 0910JST started.

![quick_result_IPdcdamp_IPsc_BFdamp_BFsc](https://user-images.githubusercontent.com/37787512/65366207-df6b5a00-dc5b-11e9-8d5a-32431b65c4ac.png)


- Until 0940JST.

**Comment by YoshinoriFujii** [comment]
### Again, IPdcdamp + IPsc + BFdamp + BFsc
- at 10:35JST started.
![config_IPdcdamp_IPsc_BFdamp_BFsc_1051JST](https://user-images.githubusercontent.com/37787512/65366359-ca8fc600-dc5d-11e9-87e3-0be483bfa370.png)

![quick_result_IPdcdamp_IPsc_BFdamp_FBsc_from1051JST](https://user-images.githubusercontent.com/37787512/65366714-98cd2e00-dc62-11e9-962f-cc899d3a6d02.png)

![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_1125JST](https://user-images.githubusercontent.com/37787512/65366716-9b2f8800-dc62-11e9-8e99-a07e80eb4837.png)

- orange: w/o BFdamp (with corrected LVDT)
- ime: w/ BFdamp (with corrected LVDT)
  - damping for ITMX looked not effective.

- until 11:50JST

---
from 12:05, only EX-BFdamp is used.
Until 12:18JST.

**Comment by YoshinoriFujii** [comment]
### Again and again, IPdcdamp + IPsc + BFdamp + BFsc

- try to modify the BFloops, especially for ITMX"s ,
![ITMX_BFLdamp_modification_1222JST](https://user-images.githubusercontent.com/37787512/65367326-88b94c80-dc6a-11e9-9ecd-00737b4b84dc.png)

- the resG frequency was changed from 146 mHz to 156mHz.

---
- from 12:29JST to12:56JST:
![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_until1256JST](https://user-images.githubusercontent.com/37787512/65367651-91f8e800-dc6f-11e9-9d43-56dcf234605b.png)

- zoom-in
![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_until1256JST_v2](https://user-images.githubusercontent.com/37787512/65367730-fec0b200-dc70-11e9-99b7-b8dfef292fb3.png)

- coherence check
![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_until1256JST_v3](https://user-images.githubusercontent.com/37787512/65367781-13ea1080-dc72-11e9-9cd0-3d34446ab485.png)

until 14:05JST

**Comment by YoshinoriFujii** [comment]
### check the BFdamping performance
- opened the EX-BF-loops at 14:05JST
![ETMX_BFdamp-LT_on_off_comp_1216JST](https://user-images.githubusercontent.com/37787512/65368402-a3e08800-dc7b-11e9-913d-6211c81eb755.png)
- It looked the filters themselves were working properly.
  => not much effective?

**Comment by YoshinoriFujii** [comment]
### Again and again, IPdcdamp + IPsc + BFdamp + BFsc
- At 14:25JST started:
![config_IPdcdamp_IPsc_BFdamp_BFsc_1427JST](https://user-images.githubusercontent.com/37787512/65368448-105b8700-dc7c-11e9-9435-4bfe0c789be3.png)

- Until 15:30JST.

![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_1429JST](https://user-images.githubusercontent.com/37787512/65371687-1d3ea180-dca1-11e9-90d6-195762c3ac14.png)

![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_1429JST_v2](https://user-images.githubusercontent.com/37787512/65371694-2d568100-dca1-11e9-950f-05e5e3c10193.png)

- [ ] Xarm has a high coherence with IP-T? actually, the local damping of IP-T for the both suspension looks not enough?

=> Do check fr next.

---
- Other stuffs to be checked:
- [ ] is a velocity damp is used BF-loop properly?
- [ ] The axes of X-arm, IT and EX suspension are aligned?

**Comment by YoshinoriFujii** [comment]
### log on 2019.9.22

![写真 2019-09-22 11 15 58](https://user-images.githubusercontent.com/37787512/65381404-908cf580-dd2b-11e9-914f-7d7f8c0c51b6.png)

- green: today's
- the others: Sep. 21st's
![ground_motion_20190922_1125JST](https://user-images.githubusercontent.com/37787512/65381416-d5b12780-dd2b-11e9-98e6-a0f555128b92.png)

---

- At 18:00
![20190922_status](https://user-images.githubusercontent.com/37787512/65386529-dc658c00-dd77-11e9-9f89-d37d96110bb9.png)

- About the ground motion:
  - blue and magenta: 2019.9.21 measurement
  - brown: in the morning on 2019.9.22
  - lime: the latest one
- [ ] why only ITMY looks much noisier than the others?

**Comment by YoshinoriFujii** [comment]
#### 2019.9.23

After taking care of 0.4Hz peak in BF-/T (believing they went away..), locked X-arm cavity:
#### from 15:33JST.
IPdcdamp + IPsc + BFdamp + BFsc for both L and T dof.

Until 16:29JST

**Comment by YoshinoriFujii** [comment]
#### from 16:47JST.
IPdcdamp + IPsc + BFsc for both L and T dof.
wait NOW!
FYI, X-arm locked during:
16:56 - 17:00 
17:09 - 17:13

---
- gif SC has started fomr 20:43 with gain1.4
- at 2057JST, opened GIFsc path
- at 21:09JST, gifSc was on with gain 1.
- at 21:22JST, gifSC with gain 1.2 started.
![gifsc_gain1 2](https://user-images.githubusercontent.com/37787512/65426049-7433aa80-de4a-11e9-8b63-1e83a1313ba1.png)

- at 21:34JST, gifSc with gain 0.8 started,
![gifSC_gain_0 8](https://user-images.githubusercontent.com/37787512/65426728-c1644c00-de4b-11e9-9e2e-b0f46b495417.png)


- at 21:46JST, gifSc with gain 1.1 started,
-at 22:35JST, gifSC with gain 1, with IPL-gain 0.5 started.

**Comment by YoshinoriFujii** [comment]
### Seismometer sensor correction check on 2019.9.25
---
#### From 2:28JST, IPdcdamp + IPsc + BFdamp + BFsc
- /users/VIS/TypeA/general/LogNotes/20190925/IPdcdamp_IPsc_BFdamp_BFsc_Xarm_locked_from0233JST.xml

- Spectrum shape -> similar to gifSC one?
- from 100mHz to200Hz, is from a stuff except for ground differential motion 
![IPdcdamp_IPsc_BFdamp_BFsc_0233JST](https://user-images.githubusercontent.com/37787512/65539086-b0970180-df43-11e9-9dae-7638d6efaefd.png)

  - よくわからないこと
    - IXではIP-LVDT-corrとIP-ACCとがよく一致して見える(at ~0.2Hz band)一方、EXではIP-LVDT-corrとIP-GEOとがあまり一致していないように見えること。
      - [ ] センサーの軸と地震計の軸が違うから？そうだと、なんでIXはそんなにあったの?
![IPdcdamp_IPsc_BFdamp_BFsc_0233JST_ground_motion_local_sensor_signals](https://user-images.githubusercontent.com/37787512/65540575-9f9bbf80-df46-11e9-8604-281d11e8599d.png)




### stopped at 03:33JST

**Comment by YoshinoriFujii** [comment]
### From 3:37JST, IPdcdamp + IPsc + BFsc

- /users/VIS/TypeA/general/LogNotes/20190925/IPdcdamp_IPsc_BFdamp_BFsc_Xarm_locked_from0233JST.xml

![IPdcdamp_IPsc_BFsc_0338JST](https://user-images.githubusercontent.com/37787512/65545207-d924f880-df4f-11e9-8940-c098c507a431.png)

- red: IPdcdamp + IPsc + BFsc
- blue: IPdcdamp + IPsc + BFdamp + BFsc

![IPdcdamp_IPsc_BFsc_0338JST_ground_motion](https://user-images.githubusercontent.com/37787512/65545385-37ea7200-df50-11e9-9ca4-a00bc259668e.png)
- blue: measured on September 22th
- brown: measured on September 23th
- lime: measured on September 24th, IPdcdamp + IPsc + BFdamp + BFsc case
- magenta: measured on September 25th, IPdcdamp + IPsc + BFsc case

  - It seems that when the ground motion is quiet, the BF-loop introduces ground motion.
    - Is this because the sensor correction is not done properly?

**Comment by YoshinoriFujii** [comment]
### From 4:39JST, IPdcdamp  + BFsc

- /users/VIS/TypeA/general/LogNotes/20190925/IPdcdamp_IPsc_BFsc_Xarm_locked_from0233JST.xml
  - red: IPdcdamp + IPsc + BFsc
  - blue: IPdcdamp + IPsc + BFdamp + BFsc
  - magenta: IPdcdamp

![IPdcdamp_BFsc_Xarm_locked_0447JST](https://user-images.githubusercontent.com/37787512/65548318-39b73400-df56-11e9-9758-371930cc7c01.png)

![IPdcdamp_BFsc_Xarm_locked_0447JST_ground_motion](https://user-images.githubusercontent.com/37787512/65548329-3de35180-df56-11e9-8bef-bf8dbc8e3c5f.png)

#### stopped at 05:40JST

**Comment by YoshinoriFujii** [comment]
### From 5:45JST, IPdcdamp + GIFsc
- with GIFsc gain 1
- w/o local sensor correction paths

![IPdcdamp_GIFsc_0545JST](https://user-images.githubusercontent.com/37787512/65551995-290abc00-df5e-11e9-96d1-b48885ae4dcf.png)
![IPdcdamp_GIFsc_0545JST_ground](https://user-images.githubusercontent.com/37787512/65551997-2ad47f80-df5e-11e9-973f-c89cf0bd1769.png)



#### stopped at 06:50JST

**Comment by YoshinoriFujii** [comment]
## Brief summary of Sep. 24th measurement

### 1. (IPdcdamp + IPsc + BFdamp + BFsc) vs. (IPdcdamp + IPsc)
https://github.com/YoshinoriFujii/Weekly-task/issues/23#issuecomment-534692366

### 2. (IPdcdamp + IPsc + BFdamp + BFsc) vs. (IPdcdamp + IPsc) vs. (IPdcdamp)
https://github.com/YoshinoriFujii/Weekly-task/issues/23#issuecomment-534719849

- The BF loops suppressed the X-arm cavity signal when the weather was so stoomy.
- If the ground motion was like at 50%-tile, it seems there is not improvement, rather the Xarm RMS would become less improved.
---
### 3. strainmeter-SC vs. seismometer-sc
![brief_summary_20190927](https://user-images.githubusercontent.com/37787512/65741017-b9dfc400-e125-11e9-8441-f8ce5df0b36d.png)

- The residuals:
  - 200mHz bump in seismometer-sc should be  
  - 150mHz, 400mHz, 700mHz: dip at IPexc-TF.

![ETMX_IPL_exc_20190927JST](https://user-images.githubusercontent.com/37787512/65741232-6f127c00-e126-11e9-81c3-afb0d46076ae.png)

  - ..kill with TM2IP or BF2IP?
  - 1Hz is to be taken case of?

**Comment by YoshinoriFujii** [comment]
ITMX:
- it looks there is some coupling to IPT
![image](https://user-images.githubusercontent.com/37787512/65766675-ac96f980-e166-11e9-98b2-f612b9183650.png)

**Comment by YoshinoriFujii** [comment]
### btw, the Sc gain of ITMX-IPT was 1.1176. Does this make the worse coupling?
- It looks no..?
- ITMX:
![ITMX_mechanical_coupling_comp_w_wo_scgain](https://user-images.githubusercontent.com/37787512/65838466-58467200-e33e-11e9-8b1e-f16e7c6abdbe.png)

- ETMX:
![ETMX_mechanical_coupling_comp_w_wo_scgain](https://user-images.githubusercontent.com/37787512/65838479-8035d580-e33e-11e9-95b1-579e5a9f21fa.png)

**Comment by YoshinoriFujii** [comment]
### Note:
Significant Wave Height:
https://www.jma-net.go.jp/kanazawa/mame/nami/nami.html

**Comment by YoshinoriFujii** [comment]
### Note on 2019.11.26

- comparison the displacement transfer function from the ground to IP-satge(measured by geophone)
  - see /users/VIS/TypeA/general/LogNotes/20190921/notes_20191126/

![image](https://user-images.githubusercontent.com/37787512/69595502-1175af80-1043-11ea-9981-247fde8fd61f.png)

  - IPdcdamp + IPsc + BFdamp + BFsc
![image](https://user-images.githubusercontent.com/37787512/69638760-ac4fa780-109e-11ea-8a0f-3d759f8b8f84.png)

---

  - try multiply 
  - [x] the TM/IPL and also 
  - [x] the (1yr-seismic noise), and then.
  - [ ] get the RMS.

- Note that the seismometer polarity is opposite in the above plots.
---
- see other details: https://www.evernote.com/l/AoOpH5zRVQJKhKNP_C28IzJMohTf-eYWHZs/

**Comment by YoshinoriFujii** [comment]
> try multiply
> the TM/IPL and also
> the (1yr-seismic noise), and then.

see https://www.evernote.com/l/AoOpH5zRVQJKhKNP_C28IzJMohTf-eYWHZs/
