### ISSUE TITLE
IP-T loop check for X-arm suspensions

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#24]
### background

- For IP-T
![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_1429JST_v2](https://user-images.githubusercontent.com/37787512/65381069-e65d9f80-dd23-11e9-9ae8-8830013c5799.png)

- For BF-L(/T)
![quick_result_IPdcdamp_IPsc_BFdamp_BFsc_until1256JST_v2](https://user-images.githubusercontent.com/37787512/65381065-e1005500-dd23-11e9-8f8f-85b506d7ba11.png)

---
### Todo
- For IP-T:
  - [x] modify the loops and suppress the residual peak to the same level of IP-L loops:
    - [x] ETMX
    - [x] ITMX

- For BF-L/T:
  - [ ] modify the loops to velocity damping one and see what happens:
    - [ ] ETMX
    - [ ] ITMX
    - see https://github.com/YoshinoriFujii/Weekly-task/issues/26

---
### Note:
- ITMY IP residual looks larger compared t the others. 
https://github.com/YoshinoriFujii/Weekly-task/issues/25

**Comment by YoshinoriFujii** [comment]
### log of 2019.9.22 work
- at about 10:30, ETMX-state was in ALIGNED.
- IR is not reached to EX, to be checked with commissioners.

**Comment by YoshinoriFujii** [comment]
### ETMX IP-T
- Starting point:
![ETMX_before_1151JST](https://user-images.githubusercontent.com/37787512/65381585-705f3580-dd2f-11e9-9f87-75de505f9bba.png)

---
- legend
  - (REF): before the modification
  - w/ (REF): after the modification


- 1st modification:
  - blue to red:
![ETMX_IPT_1stmodification_1207JST](https://user-images.githubusercontent.com/37787512/65381692-ac939580-dd31-11e9-9668-f8db63993dd3.png)
- result with gain 1.0
![result_1st_trial_ETMX_IPT](https://user-images.githubusercontent.com/37787512/65381858-90ddbe80-dd34-11e9-834c-b18e7ad0577c.png)

- with gain 1.5
![ETMX_IPT_before_after_gain1 5_1347JST](https://user-images.githubusercontent.com/37787512/65382421-b4f2cd00-dd3f-11e9-8fb7-5fca3614d78b.png)

  - gain 1.5 case is selected here.
  - Then now,
![ETMX_IP_T_check_after_modification_1449JST](https://user-images.githubusercontent.com/37787512/65382901-45cda680-dd48-11e9-9cb5-270b1b5165e7.png)




---
- Anyhow the RMS was suppressed according to the LVDT signal.
- [ ] But, the geophone signal was not much suppressed at 0.2Hz.. why? 
- [ ] from 1Hz to 10Hz, noise injected level was increased. This should be okay but should be checked with simulation?
  - since thi is the most upper stage and this is T dof..

**Comment by YoshinoriFujii** [comment]
### btw, the geo calibration filter has phase delay by at 0.1 Hz:

- Due to the low frequency cut-off, there is a phase delay by ~ 23deg.:
  - red: ideal one, 3.4deg at 0.1 Hz
  - blue: actually installed one: 26.25deg at 0.1Hz.
  - the difference is 22.85deg at 0.1 Hz.

![geo_calibration_fiter_check](https://user-images.githubusercontent.com/37787512/65382345-3cd7d780-dd3e-11e9-98f5-ba16f190e840.png)

- At least, the amplitude should be same as the ideal one at above 0.1Hz.

**Comment by YoshinoriFujii** [comment]
### ITMX IP-T check:
- At the starting point:
  - why the OUTPUT was being held?
![ITMX_IP_T_check_start_state](https://user-images.githubusercontent.com/37787512/65382550-2e3fef00-dd43-11e9-9336-e9bb4d743d2e.png)

![ITMX_IP_T_OUTPUT_check](https://user-images.githubusercontent.com/37787512/65383236-3866eb00-dd4d-11e9-8ab2-8d1acdbc3ee0.png)


---
- the filter was changed from blue to red colored one.
![ITMX_IP_T_1st_tria_1438JST](https://user-images.githubusercontent.com/37787512/65382768-c095c200-dd46-11e9-9565-f9507242f025.png)

- with gain 1.5
![result_ITMX_IPT_after_modification_gain_1 5_1536JST](https://user-images.githubusercontent.com/37787512/65383319-cee7dc00-dd4e-11e9-90de-78b82ed4c65c.png)

 - there was not big differences in the spectra before/after the modification. 
  - [ ] Try to check TF from ground to the stage and compare...
  - At 0.4 and 0.65 Hz peaks, there was a suppression (it seemed).
  - Here, in any case, To set same configuration for all the suspensions, I have selected red colored filter.

![ITMX_IP_T_after_modifircation_1542JST](https://user-images.githubusercontent.com/37787512/65383396-158a0600-dd50-11e9-93b9-910c1c939da8.png)
