### ISSUE TITLE
IP-L/T loop check for ITMY suspension

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#25]
### Background
- Based on the TMoplev spectra, the suspension motion at 200mHz looks large compared to the others.
![ITMY_TM_starting_point_1548JST](https://user-images.githubusercontent.com/37787512/65383438-9fd26a00-dd50-11e9-88e4-4dd6b7a49a27.png)

- What is the horn at ~180mHz?
---
### Todo
- [x] check the current spectra
- [ ] modify the IP oops if necessary

**Comment by YoshinoriFujii** [comment]
- starting point:
  - ITMY_IPdcdamp_IPsc_BFdamp_BFsc_1631JST
![ITMY_IPdcdamp_IPsc_BFdamp_BFsc_1631JST](https://user-images.githubusercontent.com/37787512/65383907-8d5b2f00-dd56-11e9-8894-c14d744952c4.png)


---
- starting point:
![ITMY_starting_point_1657JST](https://user-images.githubusercontent.com/37787512/65384195-19bb2100-dd5a-11e9-9e24-f0ae9fef509a.png)
---
- 1st trial:
![ITMY_IPL_1st_trial_1700JST](https://user-images.githubusercontent.com/37787512/65384224-9ea63a80-dd5a-11e9-9b5b-c982376db061.png)


---
- with gain 2
![ITMY_IPL_gain2_1712JST](https://user-images.githubusercontent.com/37787512/65384412-0b223900-dd5d-11e9-908b-693ccbe39605.png)

- w/ gain 1
![ITMY_gain1_wo_IPsc_1729JST](https://user-images.githubusercontent.com/37787512/65386393-2483af00-dd76-11e9-8ff0-3bcc5ea1c9d8.png)

- w/ gain 0.5
![ITMY_IP_LTloop_check_1st_gain0 5_1659JST](https://user-images.githubusercontent.com/37787512/65386421-82b09200-dd76-11e9-9aa8-646420511448.png)

---

- w/ gain 0.5, after changing the gain for BFdamp-L/T
![ITMY_after_IPLBFLTmodification_gain1_BFdamp_BFsc1850](https://user-images.githubusercontent.com/37787512/65386392-1f266480-dd76-11e9-8a52-427dd5a4680c.png)
 
 - Anyhow this is the currently implemented one.
---
- Does the sensor correction at IP-, BF-stage work properly? It looks that the subtraction is not enough.
  - [ ] check/ compare the spectra w/ and w/o SC again.

**Comment by YoshinoriFujii** [comment]
Then, now
![ITMY_IPL_after_modification_20190922](https://user-images.githubusercontent.com/37787512/65387023-af1bdc80-dd7d-11e9-9a52-d0cebcd79dec.png)

---
-Next: 
- [ ] investigate/modify the IP-T loop in necessary

**Comment by YoshinoriFujii** [comment]
- FYI, the IPTsc performance at low frequency:
![ITMY_IPTsc_monitor_0720JST](https://user-images.githubusercontent.com/37787512/65395231-0d26df00-ddd3-11e9-89eb-16ca11d34b7b.png)
