### ISSUE TITLE
reshape BF-L/T filter?

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#26]
### Todo
- From https://github.com/YoshinoriFujii/Weekly-task/issues/24
- Basically for X-arm suspensions
- check the resG impact
- check if the following peaks can be damped with BF-LVDTs
  - [ ] 0.25Hz => probably impossible
  - [x] 0.4Hz
  - [x] 0.67Hz

**Comment by YoshinoriFujii** [comment]
### On 2019.9.22 ITMY
- For ITMY, the gain was changed as any how since it seemed the feedback force *looked* relatively large:
  - [BF-L: from 1 to 0.5
  - BF-T from 1 to 0.25

**Comment by YoshinoriFujii** [comment]
### ITMX BF-L
- start:
![ITMX_BF_start_0819JST](https://user-images.githubusercontent.com/37787512/65396278-d4413700-dddf-11e9-8c3a-05c4aa5818e4.png)

- already implemented(dashed) vs. w/o BF-L damping filter:
![ITMX_wo_BFL_loop_0830JST](https://user-images.githubusercontent.com/37787512/65396336-56c9f680-dde0-11e9-8c29-b83fa1ad890b.png)

---
- already implemented(dashed) vs. BF-L damping filter (damp_sc)

![ITMX_damp_sc](https://user-images.githubusercontent.com/37787512/65396549-3bf88180-dde2-11e9-80fe-07a98f1c2e6f.png)

![ITMX_BFL_damp_sc_0853](https://user-images.githubusercontent.com/37787512/65396338-5af61400-dde0-11e9-8ad2-1fda9c0fcb98.png)

- peak(or bump) at 0.4Hz was decreased though, peaks at ~0.56Hz and ~0.8Hz appeared. To be tuned again.

---
- already implemented(dashed) vs. BF-L damping filter (damp_sc_test)
- dmap_sc - notch0.4Hz - resG0.15
![ITMX_BF_damp_sc_test](https://user-images.githubusercontent.com/37787512/65396568-5d596d80-dde2-11e9-946e-60525e68e54f.png)

![ITMX_BF_damp_sc_test_spectra_0914](https://user-images.githubusercontent.com/37787512/65396585-a01b4580-dde2-11e9-9168-02c9e31277fe.png)

- Again, peak(or bump) at 0.4Hz was decreased though, peaks at ~0.56Hz and ~0.8Hz appeared. To be tuned.

---
- already implemented(dashed) vs. BF-L damping filter (damp_sc_test)
- dmap_sc - notch0.4Hz + resG0.4102

![ITMX_BFLdamp_1012JST](https://user-images.githubusercontent.com/37787512/65397402-c513b680-ddea-11e9-9666-5012d492fae9.png)

![ITMX_BF_damp_add_resG0 4_spectra](https://user-images.githubusercontent.com/37787512/65397702-39e7f000-dded-11e9-8254-e2f8bd032676.png)
- looked improved at 0.4Hz.
  => - [ ] check the performance in long-term

**Comment by YoshinoriFujii** [comment]
### BTW, peak at 0.25Hz
- At this frequency, we have
  - BF-L/T dip in the IP-damped-mechanical TF
  - dip in vertical (GAS) TFs:
![ITMX_GAS_mechanicalTFs](https://user-images.githubusercontent.com/37787512/65397521-bb3e8300-ddeb-11e9-8e08-cacfec304222.png)
  
- According to a measurement, it seems that the peak at 0.25Hz is from vertical motion

![ITMX_0 25Hz_peak_check_1033JST](https://user-images.githubusercontent.com/37787512/65397772-c2ff2700-dded-11e9-871e-530a5f98a865.png)

  - since a the GAS filters have a dip, and thus damping with GAS filter seems difficutl.
  - [ ] How about BFV? 
  - [ ] btw, how are the control loops look like?
    => https://github.com/YoshinoriFujii/Weekly-task/issues/27

**Comment by YoshinoriFujii** [comment]
### ITMX BF T loop
- remove 0.4Hz notch

![ITMX_BF_T_removed_notch0 4Hz](https://user-images.githubusercontent.com/37787512/65398346-87fef280-ddf1-11e9-98dc-da5a94f07884.png)

![ITMX_BF_T_after_remove_notch0 4Hz_1150JST](https://user-images.githubusercontent.com/37787512/65399574-6ce3b100-ddf8-11e9-8f51-44391a7ce309.png)

- the 0.4Hz peak was damped but is it shifted? ~see the long term~
  - yes.at 0.4 Hz peak, the pjhase shift is ~0deg. The phase should be compensated for velocity damping.

---
Then, 
![ITMX_after_BF_LT_modification_1705JST](https://user-images.githubusercontent.com/37787512/65410136-869aed80-de24-11e9-85b5-8db13440c81b.png)

**Comment by YoshinoriFujii** [comment]
### ETMX BFL test
- start:
![image](https://user-images.githubusercontent.com/37787512/65402209-f64eaf80-de07-11e9-85f1-57b381fe9012.png)

![ETMX_BFL_damp_modification_1439JST](https://user-images.githubusercontent.com/37787512/65403693-e9ce5500-de0f-11e9-9606-0bb3b19c2697.png)

![image](https://user-images.githubusercontent.com/37787512/65403654-a70c7d00-de0f-11e9-8c74-c8071127fe6c.png)
- BF-: comp w/ and w/o daming at BF
- The cyan is BF-T motion though, so far, NF-L was moving as same level as BF-T.

**Comment by YoshinoriFujii** [comment]
### ETMX BF-T
- just to remove 0.4Hz peak in the spectra. 
![ETMX_BF_T_after_modification_1521JST](https://user-images.githubusercontent.com/37787512/65405018-e8a02680-de15-11e9-8a0a-6f850187b7d4.png)

- after modification
  - Not completely but improvements was there. I just stopped since this was not the crucial one now(it seemed.)
![ETMX_BFT_after modification_1523JST](https://user-images.githubusercontent.com/37787512/65405135-2f8e1c00-de16-11e9-8dbb-ac1f2e4fdccc.png)
---
Then 
![ETMX_BF_after_modification_1524JST](https://user-images.githubusercontent.com/37787512/65405180-4e8cae00-de16-11e9-96e7-7c19ee0b1ed8.png)

- go back "start" if something becomes strange.
