### ISSUE TITLE
Reshape the IPY dcdamp filter of Xarm suspensions

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#30]
### Background
- In the performance test for seicSC, it was found that IP-T and L motion coupling to Xarm cavity signal looked dominant.
- I was also found that the ITMX and ETMX-IPY loop was different each other, and one of them did not feedback a force which was proportional to the velocity.

### Todo
- shape the filters so that:
  - [ ] implement same shape filter to increase the CMMR.
  - [ ] the feedback signal is proportional to velocity 

- [ ] Check the stability
- [ ] compare the spectra w/ implemented one vs. w/ newly implemented one.

**Comment by YoshinoriFujii** [comment]
### Log on 2019.9.28
#### Modification plan

**Comment by YoshinoriFujii** [comment]
### work log on 2019.9.29
#### After implementation
- The loop stability looked okay, in the time scale of a few hours.
- spectra comparison
  - w/o controls vs. w/ previous controls:


  - w/ previous controls vs. w/new controls:

**Comment by YoshinoriFujii** [comment]
During this measurement, an earthquake was happened. since comparing the spectra became difficult, I started to check the actuator coupling of IP stage.
