### ISSUE TITLE
Check actuator coupling ratio at IP stage for Xarm suspensions

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#31]
### Background
- It was found that there was couplings from ITMX-IPT and ITMX-IPY motion to Xarm cavity signal,

### Todo
- [X] measure mechanical TFs of:
  - [X] ETMX
  - [X] ITMX

- [ ] compare how the coupling ratio is same:

**Comment by YoshinoriFujii** [comment]
### 2019.9.29

#### Before:


- ETMX: `/users/VIS/TypeA/general/LogNotes/20190929/ETMX/maechanical_coupling`
![ETMX_mechanical_coupling_before_diag-work](https://user-images.githubusercontent.com/37787512/65838103-888c1180-e33a-11e9-94e2-d9e14df1d70b.png)


- ITMX: `/users/VIS/TypeA/general/LogNotes/20190929/ITMX/maechanical_coupling`
![ITMX_mechanical_coupling_before_diag-work](https://user-images.githubusercontent.com/37787512/65838093-61354480-e33a-11e9-922f-60999c925d41.png)

  - see for the measurement files of this diagonalization work for ITMX:
`/users/VIS/TypeA/ITMX/actuator_diag/IP_LVDT/20190929/
`
![ITMX_driving_mat_before_modification](https://user-images.githubusercontent.com/37787512/65838012-3ac2d980-e339-11e9-9b54-f1544049e490.png)


#### symptom:
- In ITMX, LtoT coupling was relatively large at 0.1Hz, compared to that of ETMX.
- TtoL, Yto_the-others, it looked that there was not much (terrible) differences between ETMX and ITMX.

---

#### After:
- After working 2Hz diagonalization work,
![ITMX_driving_mat_after_modification](https://user-images.githubusercontent.com/37787512/65838014-3f878d80-e339-11e9-8a59-793c0471c26b.png)

- Comparison: before vs. after diag.
![ITMX_IPL_exc_after_modification_080922UTC](https://user-images.githubusercontent.com/37787512/65838224-e40acf00-e33b-11e9-9681-a979a199721b.png)

- It was found that there was not differences.

---
- [x] try 0.1Hz iagonalization

**Comment by YoshinoriFujii** [comment]
> try 0.1Hz diagonalization

- see `/users/VIS/TypeA/ITMX/actuator_diag/IP_LVDT/20190930/`

- The result was:
```
D =
    2.6897   -0.2661    0.7587
   -1.4823   -1.9867    0.5643
   -1.1332    2.2866    0.6682
```
---
- the mechanical (actuator coupling) was following:
- see `/users/VISsvn/TypeAtower/ITMX/Measurements/20190930/after_0.1Hz_diag/
`
- IPLexc
![IP_L_exc_wo_control](https://user-images.githubusercontent.com/37787512/65845176-13d5c900-e374-11e9-9ff3-6570346cbd75.png)

- IPTexc
![IP_T_exc_wo_control](https://user-images.githubusercontent.com/37787512/65845181-19331380-e374-11e9-93eb-17135b76d817.png)

- IPYexc
![IP_Y_exc_wo_control](https://user-images.githubusercontent.com/37787512/65845186-1cc69a80-e374-11e9-9d30-7bd3088d3057.png)

---
- A bit improved? especially from Yaw?
- But not much improved from L and T.
- Also, Q in IPT2IPT looks relatively small?

**Comment by YoshinoriFujii** [comment]
see https://github.com/YoshinoriFujii/Weekly-task/issues/32 for Y-arm suspensions.

**Comment by YoshinoriFujii** [comment]
- [ ] Try make new actuator matrix using the coupling at 0.1Hz?
