### ISSUE TITLE
Check actuator coupling ratio at IP stage for Yarm suspensions

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#32]
### Background
- After a work of checking the mechanical coupling, I started to wonder how the coupling of Yarm suspensions are. To check the status of Y-arm suspensions 

### Todo
- [ ] Check the status of mechanical actuator coupling of Y-arm suspensions.
  - [ ] ITMY
  - [ ] ETMY

**Comment by YoshinoriFujii** [comment]
### btw, before starting this work, on 2019.9.30
- I found that the steep 240Hz line was observed in both the Y-arm suspensions, and I have just removed it by adding notch to the LVDTINF filter bank.
- see `/users/VIS/TypeA/general/LogNotes/20190930/Yarm_suspension_notch240/
`
#### Before
![Yarm_suspensions_IP_LVDT_before_adding_notch240Hz](https://user-images.githubusercontent.com/37787512/65843129-e5072500-e36a-11e9-8bf1-67c551c9ed8c.png)

#### After 
![Yarm_suspensions_IP_LVDT_after_adding_notches](https://user-images.githubusercontent.com/37787512/65843136-eb959c80-e36a-11e9-8297-b9131ff20baf.png)

**Comment by YoshinoriFujii** [comment]
### ITMY
- see `/users/VISsvn/TypeAtower/ITMY/Measurements/TF/20190930
`
- This measurement was done with the seismometer sensor correction ON.
#### IP_L_exc
![IP_Lexc_wo_control](https://user-images.githubusercontent.com/37787512/65843326-0caabd00-e36c-11e9-9cde-c29edca4859c.png)

##### ちなみに
- IPLexc to TML
![IP_Lexc2TML_wo_control](https://user-images.githubusercontent.com/37787512/65843331-1f24f680-e36c-11e9-8288-0227cfe970dc.png)

#### IP_T_exc
![IP_Texc_wo_control](https://user-images.githubusercontent.com/37787512/65843450-af633b80-e36c-11e9-9fe9-ff2b7cb3caad.png)

#### IP_Y_exc
- [ ] TO BE MEASURED!

---
#### Then,
- The actuator coupling was mostly same as that of ETMX suspension, not like the ITMX's.

**Comment by YoshinoriFujii** [comment]
### ETMY
- see `/users/VISsvn/TypeAtower/ETMY/Measurements/TF/Measurements/20190930
`
- This measurement was done with the seismometer sensor correction ON.
#### IP_L_exc
![IP_Lexc_wo_control](https://user-images.githubusercontent.com/37787512/65843644-b5a5e780-e36d-11e9-93a4-9466b54ca922.png)

##### ちなみに
- IPLexc to TML
![IP_Lexc2TML_wo_control](https://user-images.githubusercontent.com/37787512/65844273-82188c80-e370-11e9-8c48-436498dca5f5.png)

#### IP_T_exc
- [ ] TO BE MEASURED!


#### IP_Y_exc
![IP_Yexc_wo_control](https://user-images.githubusercontent.com/37787512/65844319-b9873900-e370-11e9-816e-4e4282c3fdfe.png)

---
#### Then,
- The actuator coupling of ETMY was also mostly same as that of ETMX suspension, not like the ITMX's.

**Comment by YoshinoriFujii** [comment]
### For comp:

- see https://github.com/YoshinoriFujii/Weekly-task/issues/31 as well.

#### ITMY
![ITMY_IP_excTF_wo_control_comp](https://user-images.githubusercontent.com/37787512/65844545-af196f00-e371-11e9-9f4e-34c072cf9ddb.png)

#### ETMY
![IP_excTF_wo_control_comp](https://user-images.githubusercontent.com/37787512/65844468-619d0200-e371-11e9-9c93-6f91163d0658.png)
