### ISSUE TITLE
mechanical Q factor measurement

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#35]
### Todo
- measure the mechanical Q-factors for each resonant mode.
  - [x] w/o damping controls
  - [x] w/ damping controls

- First, Do finish this work at ETMX.

**Comment by YoshinoriFujii** [comment]
### Notes
- For a check with FFT:
`/users/VIS/TypeA/general/qfactor_measurement/ETMX/wo_control/mode39/MNY2TMY_hpfiltered_0.5Hz/exe_plot_asd.py`

- If you want to get filtered timeseries:
`/users/VIS/TypeA/general/qfactor_measurement/get_timeseries_filtered.py`

![test](https://user-images.githubusercontent.com/37787512/66569920-7d8d7880-eba7-11e9-8065-7c5126030748.gif)

**Comment by YoshinoriFujii** [comment]
### Log at 2019.10.11
- Since I had no idea what are the exact frequency of the mode 56 and mode 58, I tried to measure the mechanical transfer function with swept sine. However, based on the measurement, it seemed the suspension did not have those resonances at 6.0Hz.
  - [ ] Measure TF more concretely.

**Comment by YoshinoriFujii** [comment]
- The resonant frequency of #50 was identified by looking at a MNL-excited spectra:
  - In the plot (following), 2.15 Hz and 2.48Hz were the dominant ones.
  - see `/users/VIS/TypeA/general/qfactor_measurement/ETMX/wo_control/mode49/timeseries/figures`
    - Before filtering:
![tm_oplev_p_block1](https://user-images.githubusercontent.com/37787512/66618504-3ee1d780-ec14-11e9-8ff4-32c7aacbc7dd.png)
    - After filtering with a band-pass from 1.9Hz to 3.0Hz:
![tm_oplev_p_band-pass1 9to3_block1_zoomed-in](https://user-images.githubusercontent.com/37787512/66618528-54ef9800-ec14-11e9-903a-c2071f81e114.png)

**Comment by YoshinoriFujii** [comment]
### Note 0n 2019.11.1

- applying bandpass in python
  - ref: https://scipy-cookbook.readthedocs.io/items/ButterworthBandpass.html
  - test files: /users/VIS/TypeA/general/qfactor_measurement/bk/tools_bk/bp_filter_bk.py
    - its outputs: users/VIS/TypeA/general/qfactor_measurement/ETMX/wo_control/mode63_Oct11th/timeseries/test/

**Comment by YoshinoriFujii** [comment]
### Note on 2019.11.9
- how to get the time-series from KAGRA main server:
  - see https://www.evernote.com/l/AoOJksKhCtNEiZ5ym7p1npInYc1dG4eBWEg/

**Comment by YoshinoriFujii** [comment]
### Note 2019.11.12

- It was observed that one resonant peak at 9.69 Hz had longer te compared to the requirement: about 70sec.
- This peak looks appeared in the TF of MNVexc to MNV/MNPoplev/TMPoplev, and thus it might be useful to close the following loops:
  - MNVps to MNV
  - TMPoplev to MNV

- [x] Just try

---
- FYI, the transfer functions:
![image](https://user-images.githubusercontent.com/37787512/68636392-aefaba80-053e-11ea-9bbf-4f54782151d3.png)

---
- [X] This was damped with a BP-comb filter using TMPoplev and MNV actuator.
  - see https://docs.google.com/spreadsheets/d/1VoEfaNRhGDV501i5V56EScmZ8ik1PI-ZFldY0ue5di4/edit#gid=0
  - see also https://docs.google.com/spreadsheets/d/1roQkUBhXvQ-Y1gkTwliK7Gg17kzqKy_00ZoyPeD7AzA/edit#gid=0

**Comment by YoshinoriFujii** [comment]
### Note on 2019.11.29

- It was found that another mode had longer te than the requirement, i.e., 60sec.
  - mode#43, 1.5Hz (T): ~200sec.
    - I would write that: 
`"This can be damped with a BP-comb filter '(MNP to MNR etc). So far, this is not issued for the lock-acquisition, and thus nt much attention was paid."
`

---

- Some unexpected modes are found.
  - Based on a model which does not include the heat-link and its VIS.
    - 0.14Hz in Yaw, te was about 167sec
    - This peak was seen in BFY2BFY loop (with I-loops were closed), and the BFY loop (red-colored one) should work for this:
![image](https://user-images.githubusercontent.com/37787512/69545118-7d6cff00-0fd4-11ea-8194-00a0e7e6bfae.png)
     - However, around this peak there was so small coherence (it is natural though..)
![image](https://user-images.githubusercontent.com/37787512/69545666-96c27b00-0fd5-11ea-86d2-3625dfe75a3f.png)

  - How this should be treated:
    - [ ] say that "only for this mode, the requirement is not met. It would be true that this mode would be hardly excited and also its te is like 3 min., not the ridiculously long one, and thus, for now it is okay. Actually this mode was found in BF_LVDT signal (in Yaw), hwever, this peak was not found at the TM stage. Further improvement should be done though. For lock acquisition for now should be okay."
      - [ ] いや、でもBF揺れたら最終的にTMも揺れるよね。どこで運動量保存してるの？によるけど、どこで？
   ~~- [ ] Or, measure it again with larger amplitude and see the result.~~
    - [ ] Actually what is this mode? where comes from?

![image](https://user-images.githubusercontent.com/37787512/69548269-5f0a0200-0fda-11ea-8b6f-fd6bbcb750df.png)

**Comment by YoshinoriFujii** [comment]
### Result
- resonant frequency vs. 1/e decay time constant:
![te_f0_both](https://user-images.githubusercontent.com/37787512/69697059-e82d5000-1124-11ea-9d25-8d2a94b00428.png)

---
- mode number in a model vs. 1/e decay time constant:
  - This model does NOT have the information of heat links and its VIS.
  - A few (it looks 3.) unknown modes were found and thus I just put #76 for one of it.
  - The others were NOT plotted in the bellow.
![mode_f0_both](https://user-images.githubusercontent.com/37787512/69697050-e4013280-1124-11ea-83e5-a70b09da43d0.png)
