### ISSUE TITLE
Is the Arm-suspensions' axes aligned to each arm-cavity axis?

### ISSUE THREAD

**Issue by YoshinoriFujii** [YoshinoriFujii/Weekly-task#36]
### Todo
- push the IP in dc along with its L- and T- axis and see the response to the Xarm-cavity signal.
  - [x] ETMX
  - [x] ITMX
  - [ ] ETMY
  - [ ] ITMY

- shake the suspension with lower frequency along with its L- and T- axis and see the response to the Xarm-cavity signal.
  - [x] ETMX
  - [x] ITMX
  - [x] ETMY
  - [ ] ITMY
---
ref: Fig 5 in https://earth-planets-space.springeropen.com/track/pdf/10.1186/s40623-017-0660-0

**Comment by YoshinoriFujii** [comment]
> push the IP in dc along with its L- and T- axis and see the response to the Xarm-cavity signal.

- see `/users/VIS/TypeA/general/axis_check/20190928/`
- I conducted it and measured the time-series, however, the trend was much affected with the ground motion(*1).
 - For the Xarm suspensions, we can compensate the ground-motion-trend by using the strainmeter, however, at that time the strainmeter was not functional for a technical problem.
    - Actually it seemed that for the first 30min of the ETMX trend data, it was working though.

(*1) This means motion measured by strainmeter. we are not sure if this is the truely the ground motion though. I could be a tilt due to 気圧変化?. 

- [ ] **This measurement is to be done again with the seismometer signal and then to be comapred to the shaking method.**

---

#### ETMX
![timeseries_test](https://user-images.githubusercontent.com/37787512/66800461-2e04cf00-ef50-11e9-8387-8691880819c5.png)

---

#### ITMX
![timeseries_test](https://user-images.githubusercontent.com/37787512/66800471-3826cd80-ef50-11e9-92cd-4d74d4623bb0.png)

---
- One trial was done here by applying detrend function in matlab:
`/users/VIS/TypeA/general/axis_check/20190928/ITMX/scripts/IP_L_xarm_axischeck1.m`
  - According to this calculation the offset of the ITMX-IP-L from the Xarm-cavity axis was:

**Comment by YoshinoriFujii** [comment]
> Shake the suspension with lower frequency along with its L- and T- axis and see the response to the Xarm-cavity signal.

- see `/users/VIS/TypeA/general/axis_check/20191009/`
- I injected 10mHz sinusoidal signal to IP-actuators along with its L and T axis, and then obtained the coupling ratio to the Xarm-cavity signal or so.
  - 10mHz was selected from a plot in the above [1]; since at that frequency it looked that the effect of the ground motion was relatively small.
- This was done with ETMX/ITMX/ETMY-suspensions.


![写真 2019-10-16 4 48 21](https://user-images.githubusercontent.com/37787512/66865392-18d08480-efd2-11e9-8faf-08f043172eec.jpg)

---
#### ETMX
##### IPL_ecxc
![axis_check_Xarm_20191009_EXIPLexc](https://user-images.githubusercontent.com/37787512/66801011-7d4bff00-ef52-11e9-82c7-abb21ae384ab.png)
##### IPT_ecxc
![axis_check_Xarm_20191009_EXIPTexc](https://user-images.githubusercontent.com/37787512/66801021-8937c100-ef52-11e9-8c4f-14ee29dfaf46.png)

---

#### ITMX
##### IPL_ecxc
![axis_check_Xarm_20191009_IXIPLexc](https://user-images.githubusercontent.com/37787512/66801027-92c12900-ef52-11e9-8c30-06a3416febf8.png)
##### IPT_ecxc
![axis_check_Xarm_20191009_EXIPTexc](https://user-images.githubusercontent.com/37787512/66801084-cb610280-ef52-11e9-88ad-96293af88568.png)

---

#### ETMY
##### IPL_ecxc
![axis_check_Xarm_20191009_EYIPLexc](https://user-images.githubusercontent.com/37787512/66865192-b1b2d000-efd1-11e9-81de-eb8676d0395a.png)

##### IPT_ecxc
![axis_check_Xarm_20191009_EYIPTexc](https://user-images.githubusercontent.com/37787512/66801042-9fde1800-ef52-11e9-9089-7bdf1bca1bb9.png)

**Comment by YoshinoriFujii** [comment]
### Continued about the shaking method:
- I estimated the angle offset of the IP-L axis from the Xarm cavity axis.
  - [X] arctan( { (Xarm / IPT)_IP_Texc } / { (Xarm / IPL)_IP_Lexc } )
    - see `/users/VIS/TypeA/general/axis_check/20191009/outputs/2Xarm/ETMX_IP2Xarm.txt`
    - see `/users/VIS/TypeA/general/axis_check/20191009/outputs/2Xarm/ITMX_IP2Xarm.txt`
    - see `/users/VIS/TypeA/general/axis_check/20191009/outputs/2Yarm/ETMY_IP2Yarm.txt`

---
 - Note:
    - older info. was calculated with: if abs(phs) > 150deg: tf = -1*tf
      - They are in `/users/VIS/TypeA/general/axis_check/20191009/outputs/bk/`
    - the newer one is done with : if abs(phs) > 90deg: tf = -1*tf
---
#### ETMX
<details><summary>older info.</summary><div>

```
config1: ETMX_IP_Lexc_2Xarm
tf1, Xarm / IPL at 1.0e-02 Hz: -9.794e-01
phs diff, Xarm / IPL at 1.0e-02 Hz: 179.841 deg
config2: ETMX_IP_Texc_2Xarm
tf2, Xarm / IPT at 1.0e-02 Hz: 8.459e-02
phs diff, Xarm / IPT at 1.0e-02 Hz: 3.726 deg

arctan2( tf2, tf1 ):  175.064 deg
```
</div></details>

```
config1: ETMX_IP_Lexc_2Xarm
tf1, Xarm / IPL at 1.0e-02 Hz: -9.794e-01
phs diff, Xarm / IPL at 1.0e-02 Hz: 179.841 deg
config2: ETMX_IP_Texc_2Xarm
tf2, Xarm / IPT at 1.0e-02 Hz: 8.459e-02
phs diff, Xarm / IPT at 1.0e-02 Hz: 3.726 deg

arctan2( tf2, tf1 ):  175.064 deg
```


#### ITMX
<details><summary>older info.</summary><div>

```
config1: ITMX_IP_Lexc_2Xarm
tf1, Xarm / IPL at 1.0e-02 Hz: -1.047e+00
phs diff, Xarm / IPL at 1.0e-02 Hz: 179.332 deg
config2: ITMX_IP_Texc_2Xarm
tf2, Xarm / IPT at 1.0e-02 Hz: 1.492e-01
phs diff, Xarm / IPT at 1.0e-02 Hz: -45.751 deg

arctan2( tf2, tf1 ):  171.895 deg
```
</div></details>

```
config1: ITMX_IP_Lexc_2Xarm
tf1, Xarm / IPL at 1.0e-02 Hz: -1.047e+00
phs diff, Xarm / IPL at 1.0e-02 Hz: 179.332 deg
config2: ITMX_IP_Texc_2Xarm
tf2, Xarm / IPT at 1.0e-02 Hz: 1.492e-01
phs diff, Xarm / IPT at 1.0e-02 Hz: -45.751 deg

arctan2( tf2, tf1 ):  171.895 deg
```


#### ETMY 
<details><summary>older info.</summary><div>

```
config1: ETMY_IP_Lexc_2Yarm
tf1, Yarm / IPL at 1.0e-02 Hz: -1.093e+00
phs diff, Yarm / IPL at 1.0e-02 Hz: 178.544 deg
config2: ETMY_IP_Texc_2Yarm
tf2, Yarm / IPT at 1.0e-02 Hz: 1.047e-01
phs diff, Yarm / IPT at 1.0e-02 Hz: 11.752 deg

arctan2( tf2, tf1 ):  174.530 deg
```
</div></details>

```
config1: ETMY_IP_Lexc_2Yarm
tf1, Yarm / IPL at 1.0e-02 Hz: -1.093e+00
phs diff, Yarm / IPL at 1.0e-02 Hz: 178.544 deg
config2: ETMY_IP_Texc_2Yarm
tf2, Yarm / IPT at 1.0e-02 Hz: 1.047e-01
phs diff, Yarm / IPT at 1.0e-02 Hz: 11.752 deg

arctan2( tf2, tf1 ):  174.530 deg
```

- [ ] Need to check the definition of Yarm-cavity signal.
---
- I also tried to check the each stage axis are aligned to IP-axis by the following:
  - [x] arctan( { (TML / IPT)_IP_Texc } / { (TML / IPL)_IP_Lexc } )
- see `/users/VIS/TypeA/general/axis_check/20191009/outputs/2TM/*`

#### ETMX
<details><summary>older info.</summary><div>

```
config1: ETMX_IP_Lexc_2TM
tf1, TM / IPL at 1.0e-02 Hz: 1.257e+00
phs diff, TM / IPL at 1.0e-02 Hz: -2.625 deg
config2: ETMX_IP_Texc_2TM
tf2, TM / IPT at 1.0e-02 Hz: -1.300e-01
phs diff, TM / IPT at 1.0e-02 Hz: -171.102 deg

arctan2( tf2, tf1 ):  -5.903 deg
```
</div></details>

```
config1: ETMX_IP_Lexc_2TM
tf1, TM / IPL at 1.0e-02 Hz: 1.257e+00
phs diff, TM / IPL at 1.0e-02 Hz: -2.625 deg
config2: ETMX_IP_Texc_2TM
tf2, TM / IPT at 1.0e-02 Hz: -1.300e-01
phs diff, TM / IPT at 1.0e-02 Hz: -171.102 deg

arctan2( tf2, tf1 ):  -5.903 deg
```

#### ITMX
<details><summary>older info.</summary><div>

```
config1: ITMX_IP_Lexc_2TM
tf1, TM / IPL at 1.0e-02 Hz: 1.449e+00
phs diff, TM / IPL at 1.0e-02 Hz: -3.059 deg
config2: ITMX_IP_Texc_2TM
tf2, TM / IPT at 1.0e-02 Hz: 1.354e-01
phs diff, TM / IPT at 1.0e-02 Hz: 101.693 deg
phs diff is not like 0 or 180deg. Please keep in mind the coherence etc.

arctan2( tf2, tf1 ):  5.340 deg
```
</div></details>

```
config1: ITMX_IP_Lexc_2TM
tf1, TM / IPL at 1.0e-02 Hz: 1.449e+00
phs diff, TM / IPL at 1.0e-02 Hz: -3.059 deg
config2: ITMX_IP_Texc_2TM
tf2, TM / IPT at 1.0e-02 Hz: -1.354e-01
phs diff, TM / IPT at 1.0e-02 Hz: 101.693 deg

arctan2( tf2, tf1 ):  -5.340 deg
```


---

  - [x] arctan( { (BFL / IPT)_IP_Texc } / { (BFL / IPL)_IP_Lexc } )
    - see `/users/VIS/TypeA/general/axis_check/20191009/outputs/2BFL/*`

#### ETMX 
<details><summary>older info.</summary><div>

```
config1: ETMX_IP_Lexc_2BF
tf1, BFL / IPL at 1.0e-02 Hz: 8.782e-01
phs diff, BFL / IPL at 1.0e-02 Hz: -0.446 deg
config2: ETMX_IP_Texc_2BF
tf2, BFL / IPT at 1.0e-02 Hz: 1.465e-02
phs diff, BFL / IPT at 1.0e-02 Hz: -130.699 deg
phs diff is not like 0 or 180deg. Please keep in mind the coherence etc.

arctan2( tf2, tf1 ):  0.956 deg
```
</div></details>

```
config1: ETMX_IP_Lexc_2BF
tf1, BFL / IPL at 1.0e-02 Hz: 8.782e-01
phs diff, BFL / IPL at 1.0e-02 Hz: -0.446 deg
config2: ETMX_IP_Texc_2BF
tf2, BFL / IPT at 1.0e-02 Hz: -1.465e-02
phs diff, BFL / IPT at 1.0e-02 Hz: -130.699 deg

arctan2( tf2, tf1 ):  -0.956 deg
```

#### ITMX 
<details><summary>older info.</summary><div>

```
config1: ITMX_IP_Lexc_2BF
tf1, BFL / IPL at 1.0e-02 Hz: 1.061e+00
phs diff, BFL / IPL at 1.0e-02 Hz: -1.140 deg
config2: ITMX_IP_Texc_2BF
tf2, BFL / IPT at 1.0e-02 Hz: 5.537e-02
phs diff, BFL / IPT at 1.0e-02 Hz: 81.916 deg
phs diff is not like 0 or 180deg. Please keep in mind the coherence etc.

arctan2( tf2, tf1 ):  2.987 deg
```
</div></details>

```
config1: ITMX_IP_Lexc_2BF
tf1, BFL / IPL at 1.0e-02 Hz: 1.061e+00
phs diff, BFL / IPL at 1.0e-02 Hz: -1.140 deg
config2: ITMX_IP_Texc_2BF
tf2, BFL / IPT at 1.0e-02 Hz: 5.537e-02
phs diff, BFL / IPT at 1.0e-02 Hz: 81.916 deg

arctan2( tf2, tf1 ):  2.987 deg
```

---
  - [x] arctan( { (BFT / IPL)_IP_Lexc } / { (BFT / IPT)_IP_Texc } )
    - see `/users/VIS/TypeA/general/axis_check/20191009/outputs/2BFT/*`

#### ETMX 
<details><summary>older info.</summary><div>

```
config1: ETMX_IP_Texc_2BF
tf1, BFT / IPT at 1.0e-02 Hz: 8.368e-01
phs diff, BFT / IPT at 1.0e-02 Hz: -1.007 deg
config2: ETMX_IP_Lexc_2BF
tf2, BFT / IPL at 1.0e-02 Hz: 1.886e-01
phs diff, BFT / IPL at 1.0e-02 Hz: -5.865 deg

arctan2( tf2, tf1 ):  12.701 deg
```
</div></details>

```
config1: ETMX_IP_Texc_2BF
tf1, BFT / IPT at 1.0e-02 Hz: 8.368e-01
phs diff, BFT / IPT at 1.0e-02 Hz: -1.007 deg
config2: ETMX_IP_Lexc_2BF
tf2, BFT / IPL at 1.0e-02 Hz: 1.886e-01
phs diff, BFT / IPL at 1.0e-02 Hz: -5.865 deg

arctan2( tf2, tf1 ):  12.701 deg
```

#### ITMX 
<details><summary>older info.</summary><div>

```
config1: ITMX_IP_Texc_2BF
tf1, BFT / IPT at 1.0e-02 Hz: 9.824e-01
phs diff, BFT / IPT at 1.0e-02 Hz: 2.063 deg
config2: ITMX_IP_Lexc_2BF
tf2, BFT / IPL at 1.0e-02 Hz: 1.420e-01
phs diff, BFT / IPL at 1.0e-02 Hz: 43.273 deg

arctan2( tf2, tf1 ):  8.227 deg
```
</div></details>

```
config1: ITMX_IP_Texc_2BF
tf1, BFT / IPT at 1.0e-02 Hz: 9.824e-01
phs diff, BFT / IPT at 1.0e-02 Hz: 2.063 deg
config2: ITMX_IP_Lexc_2BF
tf2, BFT / IPL at 1.0e-02 Hz: 1.420e-01
phs diff, BFT / IPL at 1.0e-02 Hz: 43.273 deg

arctan2( tf2, tf1 ):  8.227 deg
```

**Comment by YoshinoriFujii** [comment]
### summary of the above:
- Plotting scripts are `/users/VIS/TypeA/general/axis_check/20191009/exe_plot_axes*.py`

---
#### Each L-axis compared to Xarm cavity

| ITEMX | ETMX |
| --- | --- |
| ![axis_check_ITMX](https://user-images.githubusercontent.com/37787512/66863241-8e862180-efcd-11e9-98d4-163174b7633b.png) | ![axis_check_ETMX](https://user-images.githubusercontent.com/37787512/66863181-70202600-efcd-11e9-8d44-6183582fbacf.png) |

---

 #### If we believe that IP-T axis is purely orthogonal to IP-L axis:
| ITEMX | ETMX |
| --- | --- |
| ![axis_check_ITMX_withT](https://user-images.githubusercontent.com/37787512/66863489-110ee100-efce-11e9-99c9-199ea73d5fcc.png) | ![axis_check_ETMX_withT](https://user-images.githubusercontent.com/37787512/66863465-06544c00-efce-11e9-961a-b84b57172114.png) |

---
### Todo for next
- Check if the above is real
  - [ ] by measuring the transfer functions again after rotating the suspension axes.
  - [ ] by try Bruco with the Xarm after rotating the suspension axes.
  - [ ] anything else?

**Comment by YoshinoriFujii** [comment]
Some URL for reference used for the above:
- for polar plot: https://matplotlib.org/3.1.1/gallery/misc/transoffset.html#sphx-glr-gallery-misc-transoffset-py
- for arrowing: http://tanukigraph.hatenablog.com/entry/2017/12/25/224725
- for legend anchoring: https://qiita.com/matsui-k20xx/items/291400ed56a39ed63462
- Tips for Github Markdown: https://qiita.com/chezou/items/b62053636fb62a8b62a5

**Comment by YoshinoriFujii** [comment]
- On 2019.10.16
  - comments at the briefing:
    - For the check of the coupling, only TtoL coupling is necessary.
      -> LtoL was measured to get the information of angle. and for a sanity check.
